name: CDX__Experiments
title: CDX
org: ReadyTalk
base_url: ''
interpolate: false
haml:
  :ugly: true

aciidoctor:
  :safe: safe
  :attributes:
    sitename: CDXExperiments
    base_url: ''
    ctx_path: ''
    id_prefix: ''
    idseparator: ''
    sectanchors: ''
    icons: font
